// Static build for fun.croft.ing (front-plan Phase 1): esbuild-bundle the
// vanilla-TS chrome into one app.js, then emit a per-game static entry page
// (`/<id>/index.html`) plus the home page (`/`). Per-game static pages give
// clean, shareable, new-tab-able URLs with no client router or Pages 404 hack.
// A second bundle (how-to.js) powers the shared "How to play" page (`/how-to/`).
import { build } from "esbuild";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, "dist");

// Game entry pages: "" is the home/drawer page (no game mounted); the rest carry
// <body data-game> so the chrome knows what to mount.
const GAME_PAGES = ["", "placeholder", "solitaire", "match3", "cribbage"];

// Pre-paint theme resolution: set [data-theme] before first paint so the felt
// table never flashes the wrong theme. Same rule as src/theme.ts resolveTheme.
const THEME_INIT = `(function(){try{var s=localStorage.getItem('fun-theme');var d=(s==='light'||s==='dark')?s:(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.setAttribute('data-theme',d);}catch(e){}})();`;

function page({ title, dataAttr = "", base, script, appDiv = false }) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <meta name="description" content="fun.croft.ing — the Croft games pond, a determinism-first local-first game shelf." />
    <meta name="theme-color" content="#1f5c3f" />
    <script>${THEME_INIT}</script>
    <link rel="stylesheet" href="${base}styles.css" />
  </head>
  <body${dataAttr}>
    ${appDiv ? '<div id="app"></div>\n    ' : ""}<script type="module" src="${base}${script}"></script>
  </body>
</html>
`;
}

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

await build({
  entryPoints: [join(root, "src/main.ts"), join(root, "src/how-to-page.ts")],
  bundle: true,
  format: "esm",
  target: "es2022",
  minify: true,
  sourcemap: true,
  outdir: dist,
  entryNames: "[name]",
});
// esbuild names outputs after their entry file; rename to the referenced names.
async function rename(from, to) {
  await cp(join(dist, from), join(dist, to));
  await rm(join(dist, from));
  if (await exists(join(dist, `${from}.map`))) {
    await cp(join(dist, `${from}.map`), join(dist, `${to}.map`));
    await rm(join(dist, `${from}.map`));
  }
}
await rename("main.js", "app.js");
await rename("how-to-page.js", "how-to.js");

// One stylesheet: tokens (the only hex) then components. The pre-paint script
// has already set [data-theme] by the time this loads.
const tokensCss = await readFile(join(root, "tokens.css"), "utf8");
const stylesCss = await readFile(join(root, "styles.css"), "utf8");
await writeFile(join(dist, "styles.css"), `${tokensCss}\n${stylesCss}`);
if (await exists(join(root, "CNAME"))) await cp(join(root, "CNAME"), join(dist, "CNAME"));

// The solitaire wasm binding (built by `npm run build:wasm` with the rustup
// toolchain — see tools/build-wasm.sh). Copied to /solitaire.wasm for fetch.
const wasm = join(root, "target/wasm32-unknown-unknown/release/solitaire_wasm.wasm");
if (await exists(wasm)) await cp(wasm, join(dist, "solitaire.wasm"));
else console.warn("note: solitaire.wasm not built yet — run `npm run build:wasm` (Phase D needs it)");

const m3wasm = join(root, "target/wasm32-unknown-unknown/release/match3_wasm.wasm");
if (await exists(m3wasm)) await cp(m3wasm, join(dist, "match3.wasm"));
else console.warn("note: match3.wasm not built yet — run `npm run build:wasm` (match-3 needs it)");

// The winnable-daily pack (Phase S) — served static so the daily mode and the
// E2E win-path fixture can fetch it. `payload[0]` is the win-path fixture.
const pack = join(root, "games/solitaire/daily-pack.json");
if (await exists(pack)) await cp(pack, join(dist, "daily-pack.json"));
else console.warn("note: daily-pack.json missing — solitaire's daily mode needs it (Phase S)");

// The match-3 clear-the-blockers winnable-daily pack (served static so the
// blockers daily mode and its E2E win-path fixture can fetch it).
const m3pack = join(root, "games/match3/blockers-pack.json");
if (await exists(m3pack)) await cp(m3pack, join(dist, "match3-blockers-pack.json"));
else console.warn("note: match3-blockers-pack.json missing — match-3's clear-the-blockers daily needs it");

const m3jpack = join(root, "games/match3/jelly-pack.json");
if (await exists(m3jpack)) await cp(m3jpack, join(dist, "match3-jelly-pack.json"));
else console.warn("note: match3-jelly-pack.json missing — match-3's clear-the-jelly daily needs it");

// Static assets: how-to screenshots (regenerated by `npm run guide:shots`) and
// the self-hosted display font.
const assets = join(root, "assets");
if (await exists(assets)) await cp(assets, join(dist, "assets"), { recursive: true });

for (const id of GAME_PAGES) {
  const dir = id ? join(dist, id) : dist;
  await mkdir(dir, { recursive: true });
  await writeFile(
    join(dir, "index.html"),
    page({
      title: id ? `Croft · fun — ${id}` : "Croft · fun",
      dataAttr: id ? ` data-game="${id}"` : "",
      base: id ? "/" : "./",
      script: "app.js",
    }),
  );
}

// The shared "How to play" page (reads ?game=<id>).
await mkdir(join(dist, "how-to"), { recursive: true });
await writeFile(
  join(dist, "how-to", "index.html"),
  page({ title: "Croft · fun — how to play", base: "/", script: "how-to.js", appDiv: true }),
);

console.log(`built app.js + how-to.js + ${GAME_PAGES.length + 1} pages -> dist/`);

async function exists(p) {
  const { access } = await import("node:fs/promises");
  return access(p).then(() => true).catch(() => false);
}
