//! B1 golden: the shape catalog is the 53-shape original, locked by count and a
//! content hash so an accidental regeneration or edit is caught. Generated by
//! `tools/extract-blockdoku-shapes.mjs` from the original AGPL `blocks.js`.

use blockdoku_core::shapes::{catalog, keys_in_tier};
use blockdoku_core::Tier;
use sha2::{Digest, Sha256};

#[test]
fn catalog_has_53_shapes_8_38_7() {
    assert_eq!(catalog().len(), 53, "total catalog size");
    assert_eq!(keys_in_tier(Tier::Standard).len(), 8, "standard pool");
    assert_eq!(keys_in_tier(Tier::Wild).len(), 38, "wild pool");
    assert_eq!(keys_in_tier(Tier::Magic).len(), 7, "magic pool");
}

#[test]
fn standard_pool_is_the_expected_eight() {
    assert_eq!(
        keys_in_tier(Tier::Standard),
        vec![
            "single",
            "line2",
            "line3",
            "l2x2",
            "l3x2",
            "t3x2",
            "square2x2",
            "z3x2",
        ]
    );
}

#[test]
fn known_shape_geometry_and_points_match_the_original() {
    let single = blockdoku_core::by_key("single").expect("single exists");
    assert_eq!(single.points, 1);
    assert_eq!(single.cell_count(), 1);

    let t3x2 = blockdoku_core::by_key("t3x2").expect("t3x2 exists");
    assert_eq!(t3x2.points, 4);
    assert_eq!(t3x2.rows(), 2);
    assert_eq!(t3x2.cols(), 3);
    assert_eq!(t3x2.max_dimension(), 3);
    // [[1,1,1],[0,1,0]]
    assert_eq!(t3x2.filled_offsets(), vec![(0, 0), (0, 1), (0, 2), (1, 1)]);

    // A magic block carries its mechanic; a standard/wild one does not.
    assert_eq!(
        blockdoku_core::by_key("bombSingle").unwrap().magic_type,
        Some("bomb")
    );
    assert_eq!(blockdoku_core::by_key("single").unwrap().magic_type, None);
    assert_eq!(
        blockdoku_core::by_key("pentominoF").unwrap().tier,
        Tier::Wild
    );
}

#[test]
fn catalog_content_hash_is_locked() {
    // A stable fingerprint of the whole catalog: key|tier|points|cells for each,
    // in source order. If this changes, the catalog changed — intended only via a
    // deliberate regeneration.
    let mut h = Sha256::new();
    for s in catalog() {
        h.update(s.key.as_bytes());
        h.update([0]);
        h.update(format!("{:?}", s.tier).as_bytes());
        h.update(s.points.to_le_bytes());
        for row in s.cells {
            h.update(row);
            h.update([0xff]);
        }
        h.update([0xfe]);
    }
    let got = hex::encode(h.finalize());
    // Locked 2026-08-01 from reference/original @ chasemp/blockdoku.
    assert_eq!(
        got, LOCKED,
        "catalog content changed; regenerate intentionally and re-lock"
    );
}

// Filled in below once observed (the test prints it on first mismatch via the
// assert message). See the accompanying `print_catalog_hash` ignored test.
const LOCKED: &str = "693b3a49358fe6434593e52116d3820f156a2a0d15f6573f41aa5eed097b96a0";

#[test]
#[ignore = "run to (re)lock the catalog hash"]
fn print_catalog_hash() {
    let mut h = Sha256::new();
    for s in catalog() {
        h.update(s.key.as_bytes());
        h.update([0]);
        h.update(format!("{:?}", s.tier).as_bytes());
        h.update(s.points.to_le_bytes());
        for row in s.cells {
            h.update(row);
            h.update([0xff]);
        }
        h.update([0xfe]);
    }
    println!("CATALOG_HASH={}", hex::encode(h.finalize()));
}
